### PR TITLE
Stop icon: support light themes and scale for higher resolution;Other…

### PR DESCRIPTION
**Pull request by a-dekker**
- Stop icon: support light themes and scale for higher resolution
- Other small layout changes
- Use clear bold text in playlist instead of more fuzzy glass effect

### CODE REVIEW

**Comment by fuchsmich** [comment]
Thank you for all the work @a-dekker . I'm sorry, but I work in one of those sectors, which is still very busy although covid-breakdown.
But I hope I will find soon some time to test your and publish your work.

**Comment by a-dekker** [comment]
Well, in the end I decided to publish my own fork: https://openrepos.net/content/ade/smpc-fork

**Comment by fuchsmich** [comment]
Maybe it would be better, if I make PRs at your repo.

I'm just working on improving the code for listing albums and so on in c++ and port all my old changes to your repo.
My plan is to support mpd from version 0.21.xx (debian stable for instance has mpd 0.21.5). All older mpd get legacy support. Otherwhise it would be too much effort for testing.

**Comment by a-dekker** [comment]
Of course PR's are welcome. Most of your changes (like mpris support) are already included.

**Comment by fuchsmich** [comment]
As said above, I will commit to your repo.

**Pull request closed without merging**
